apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    name: deployment
spec:
  selector:
    matchLabels:
      name: deployment-pod
  replicas: 3
  template:
    metadata:
      name: deployment-pod
      labels:
        name: deployment-pod
    spec:
      containers:
      - name: nginx-container
        image: nginx
