apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: myApp
spec:
  selector:
    matchLabels:
      app: nginx3
  replicas: 3
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx3
    spec:
      containers:
      - name: nginx-container
        image: nginx
