trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Terraform
  jobs:
  - job: BuildInfra
    steps:
    - task: AzureKeyVault@2
      displayName: 'Get secrets from vault'
      inputs:
        azureSubscription: azure-devops
        keyVaultName: 'zalaVault'
        secretsFilter: '*'
        runAsPreJob: false
    - task: GenerateBackendFile
      displayName: 'Generating backend.conf file'
      inputs:
        script: |
          cd $(system.defaultworkingdirectory)/7_pipeline_arch/
          echo $(storageAccountName) >> backend.conf
          cat backend.conf
