trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Terraform
  jobs:
  - job: BuildInfra
    steps:
    - task: AzureKeyVault@2
      displayName: 'Get secrets from vault'
      inputs:
        azureSubscription: azure-devops-keyvault
        keyVaultName: keyVaultZala
        secretsFilter: '*'
        runAsPreJob: false
    - task: CmdLine@2
      displayName: 'Generating backend.conf file'
      inputs:
        script: |
          cd $(system.defaultworkingdirectory)/7_pipeline_arch/
          echo $(storageAccountName) >> backend.conf
          cat backend.conf
