trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Terraform
  jobs:
  - jobs: BuildInfra
    steps:
    - task: AzureKeyVault@2
      displayName: 'Get secrets from vault'
      inputs:
        azureSubscription: azure-devops
        keyVaultName: 'zalaVault'
        secretsFilter: '*'
        runAsPreJob: false
