trigger:
- master

variables:
  storage_account_name: $(storageAccountName)

pool:
  vmImage: ubuntu-latest

stages:
- stage: Terraform
  jobs:
  - job: BuildInfra
    steps:
    - task: AzureKeyVault@2
      displayName: 'Get secrets from vault'
      inputs:
        azureSubscription: azure-devops
        keyVaultName: keyVaultZala
        secretsFilter: '*'
        runAsPreJob: false
    - task: CmdLine@2
      displayName: 'Generating backend.conf file'
      inputs:
        script: |
          cd $(system.defaultworkingdirectory)/7_pipeline_arch/
          echo "storage_account_name=$(storage_account_name)" >> backend.conf
          cat backend.conf
