trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Terraform
  jobs:
  - job: BuildInfra
    steps:
    - task: AzureKeyVault@2
      displayName: 'Get secrets from vault'
      inputs:
        azureSubscription: azure-devops
        keyVaultName: keyVaultZala
        secretsFilter: '*'
        runAsPreJob: false
    - task: CmdLine@2
      displayName: 'Generating backend.conf file'
      inputs:
        script: |
          cd $(system.defaultworkingdirectory)/7_pipeline_arch/
          echo "storage_account_name=$(storageAccountName)" >> backend.conf
          echo "container_name=$(containerName)" >> backend.conf
          echo "access_key=$(accessKey)" >> backend.conf
          echo "key=terraform.tfstate" >> backend.conf
    - task: CmdLine@2
      displayName: 'Generating terraform.tfvars'
      inputs:
        script: |
          cd $(system.defaultworkingdirectory)/7_pipeline_arch/
          echo "azure_client_id       = $(azureClientId)" >> terraform.tfvars
          echo "azure_client_secret   = $(azureClientSecret)" >> terraform.tfvars
          echo "azure_subscription_id = $(azureSubscriptionId)" >> terraform.tfvars
          echo "azure_tenant_id       = $(azureTenantId)" >> terraform.tfvars
    - task: TerraformInstaller@0
      displayName: 'Terraform INSTALL'
      inputs:
        terraformVersion: '1.0.0'
