trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Terraform
  jobs:
  - job: 'Configure Terraform'
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '1.0.0'
