trigger:
- master

variables:
  keySecret: $(tamarindo)

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: azure-devops-keyvault
    keyVaultName: "zalaVault"
    secretsFilter: "*"
    RunAsPreJob: false
- task: CmdLine@2
  inputs:
    script: echo $(keySecret) > secret.txt
- task: CopyFiles@2
  inputs:
    Contents: secret.txt
    targetFolder: "$(Build.ArtifactStagingDirectory)"
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: "$(Build.ArtifactStagingDirectory)"
    ArtifactName: "drop"
    PublishLocation: "Container"
- script: echo "Completed!"
  displayName: "Finished"
- script: |
    echo "This should works..."
    echo "Vault configured and using env vars"
  displayName: "Description"
