trigger:
- master

variables:
- group: storage_account

pool:
  vmImage: ubuntu-latest

stages:
- stage: GetTerraformFiles
  jobs:
  - job: GetTerraformFiles
    steps:
    - task: CopyFiles@2
      displayName: 'Copy terraform files to artifacts'
      inputs:
        sourceFolder: 7_pipeline_arch
        TargetFolder: '$(build.artifactstagingdirectory)/Terraform'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifacts'
      inputs:
        pathToPublish: '$(build.artifactstagingdirectory)'
        artifactName: artifacts

- stage: Terraform
  dependsOn: GetTerraformFiles
  jobs:
  - job: Terraform
    steps:
    - task: DownloadBuildArtifacts@1
      displayName: 'Download artifacts'
      inputs:
        builtType: 'current'
        downloadType: 'single'
        artifactName: artifacts
        downloadPath: '$(system.defaultworkingdirectory)'
    #- task: CmdLine@2
      #displayName: 'Creating backend.conf file'
      #inputs:
        #script: |
          #cd '$(system.defaultworkingdirectory)/artifacts/Terraform'
          #echo "storage_account_name=$(storage_account_name)" >> backend.conf
          #echo "container_name=$(container_name)" >> backend.conf
          #echo "access_key=$(access_key)" >> backend.conf
          #echo "key=$(key)" >> backend.conf
    - task: TerraformInstaller@0
      displayName: 'Terraform INSTALL'
      inputs:
        terraformVersion: '1.0.0'
    - task: TerraformTaskV2@2
      displayName: 'Terraform INIT'
      inputs:
        provider: 'azurerm'
        command: 'init'
        commandOptions: '--backend-config=backend.conf'
        workingDirectory: '$(system.defaultworkingdirectory)/artifacts/Terraform'
        backendServiceArm: 'azure-devops-keyvault'
        backendAzureRmResourceGroupName: 'vaultRG'
        backendAzureRmStorageAccountName: $(storage_account_name)
        backendAzureRmContainerName: $(container_name)
        backendAzureRmKey: $(access_key)
    - task: TerraformTaskV2@2
      displayName: 'Terraform VALIDATE'
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(system.defaultworkingdirectory)/artifacts/Terraform'
        environmentServiceNameAzureRM: 'azure-devops-keyvault'
        backendAzureRmResourceGroupName: 'vaultRG'
        backendAzureRmStorageAccountName: $(storage_account_name)
        backendAzureRmContainerName: $(container_name)
        backendAzureRmKey: $(storageaccount)
    #- task: TerraformTaskV2@2
      #displayName: 'Terraform PLAN'
      #inputs:
        #command: 'plan'
        #workingDirectory: '$(system.defaultworkingdirectory)/artifacts/Terraform'
        #environmentServiceNameAzureRM: 'azure-devops-keyvault'
        #backendAzureRmResourceGroupName: 'vaultRG'
        #backendAzureRmStorageAccountName: 'juanc'
        #backendAzureRmContainerName: 'blobcontainer'
        #backendAzureRmKey: $(storageaccount)
