trigger: none

pool:
  name: SelfHosted
  demands: Agent.OS -equals Linux

variables:
  ansibleFolder: $(System.DefaultWorkingDirectory)/azure/006_wordpress_with_ansible/ansible
  inventoryFile: $(ansibleFolder)/inventory_azure_rm.yml

stages:
- stage: Ansible

  jobs:
  - job: apply
    steps:
    - task: azureKeyVault@2
      displayName: Retrieve secrets
      inputs:
        connectedServiceName: Azure
        keyVaultName: $(keyVaultName)
        secretsFilter: appId,appSecret,appTenant,subscriptionId
        runAsPreJob: true

    - bash: |
        echo "[default]" > "$HOME/.azure/credentials"
        echo "subscription_id=$(subscriptionId)" >> "$HOME/.azure/credentials"
        echo "client_id=$(appId)" >> "$HOME/.azure/credentials"
        echo "secret=$(appSecret)" >> "$HOME/.azure/credentials"
        echo "tenant=$(appTenant)" >> "$HOME/.azure/credentials"
        APP_GTW_IP=$(az network public-ip show -n WordPressIP -g resourceGroup006 --query '{ipAddress:ipAddress}' --output tsv)
        echo "Public ip is $APP_GTW_IP"
        echo "##vso[task.setvariable variable=APP_GTW_IP]$APP_GTW_IP"
      displayName: Get Application Gateway public IP

    - task: Ansible@0
      displayName: Update/Upgrade vms
      inputs:
        ansibleInterface: agentMachine
        playbookPathOnAgentMachine: $(ansibleFolder)/playbook_init.yml
        inventoriesAgentMachine: file
        inventoryFileOnAgentMachine: $(inventoryFile)
        sudoEnabled: true
