resources:
  pipelines:
  - pipeline: 'Terraform destroy infra'
    source:

pool:
  vmImage: ubuntu-latest

stages:
- stage: agent

  jobs:
  - job: destroy
    steps:
    - checkout: none

    - task: azureKeyVault@2
      displayName: Retrieve secrets
      inputs:
        connectedServiceName: Azure
        keyVaultName: $(keyVaultName)
        secretsFilter: azdoPat
        runAsPreJob: true

    - bash: |
        PATH="/Terraform"
        curl -u :$(azdoPat) "$(azdoUrl)/Terraform/_apis/distributedtask/queues?queueNames=SelfHosted&api-version=7.0"
      displayName: Remove agent
