#resources:
  #pipelines:
  #- pipeline: 'Terraform destroy infra'
    #source:

trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: agent

  jobs:
  - job: destroy
    steps:
    - checkout: none

    - task: azureKeyVault@2
      displayName: Retrieve secrets
      inputs:
        connectedServiceName: Azure
        keyVaultName: $(keyVaultName)
        secretsFilter: azdoPat
        runAsPreJob: true

    - bash: |
        GET_AGENT_POOL_PATH="/$(projectName)/_apis/distributedtask/queues?queueNames=$(poolName)&api-version=7.0"
        POOL_ID=$(curl -u :$(azdoPat) "$(azdoUrl)$GET_AGENT_POOL_PATH" | jq '.value[0].pool.id')
        GET_AGENTS_PATH="/_apis/distributedtask/pools/$POOL_ID/agents?api-version=7.0"
        RESPONSE=$(curl -u $azdoPat "$(azdoUrl)$GET_AGENTS_PATH")
        OFFLINE_AGENTS_IDS=$(echo $RESPONSE | jq '[.value[] | select(.status != "online" ) | .id]')
        echo $OFFLINE_AGENTS_IDS
      displayName: Remove agent
