trigger: none

parameters:
- name: example
  displayName: Terraform Example
  type: string
  values:
  - 001_resource_group
  - 002_vnet
  - 003_storage_account
  - 004_linux_vm
  - 005_load_balancer
  - 006_wordpress_with_ansible
  - 007_wordpress_only_terraform
  - 008_db_migrations
  - 009_databricks
  - 100_k8s_base
  - 101_k8s_prometheus
  - 102_k8s_thanos
  - 103_k8s_alerts

stages:
- stage: Terraform

  pool:
    vmImage: ubuntu-latest

  jobs:
  - job: buildInfra
    steps:
    - task: azurekeyVault@2
      displayName: Retrieve secrets
      inputs:
        connectedServiceName: Azure
        keyVaultName: $(keyVaultName)
        secretsFilter: tf-token
        runAsPreJob: true

    - task: terraformInstaller@0
      displayName: Terraform install
      inputs:
        terraformVersion: 'latest'

    - task: replaceTokens@5
      displayName: Update token file
      inputs:
        targetFiles: $(System.DefaultWorkingDirectory)/pipelines/tfToken.json
        tokenPattern: 'azpipelines'

    - bash: |
        cd $(System.DefaultWorkingDirectory)/azure/${{ parameters.example }}/
        mv $(System.DefaultWorkingDirectory)/pipelines/tfToken.json /home/vsts/.terraform.d/credentials.tfrc.json
      displayName: Terraform login

    - task: terraformCLI@0
      displayName: Terraform init
      inputs:
        command: init
        workingDirectory: $(System.DefaultWorkingDirectory)/azure/${{ parameters.example }}/

    - task: terraformCLI@0
      displayName: Terraform fmt
      inputs:
        command: fmt
        workingDirectory: $(System.DefaultWorkingDirectory)/azure/${{ parameters.example }}/

    - task: terraformCLI@0
      displayName: Terraform validate
      inputs:
        command: validate
        workingDirectory: $(System.DefaultWorkingDirectory)/azure/${{ parameters.example }}/

    - task: terraformCLI@0
      displayName: Terraform plan
      inputs:
        command: plan
        workingDirectory: $(System.DefaultWorkingDirectory)/azure/${{ parameters.example }}/

    - task: terraformCLI@0
      displayName: Terraform apply
      inputs:
        command: apply
        commandOptions: '-auto-approve'
        workingDirectory: $(System.DefaultWorkingDirectory)/azure/${{ parameters.example }}/

    - bash: |
        terraform output subscription_id
        terraform import azurerm_resource_group.net_watcher \
          "/subscriptions/$(terraform output subscription_id)/resourceGroups/NetworkWatcherRG"
      displayName: Importing Network Watcher RG

    - bash: |
        newRunName="${{ parameters.example }}"
        echo "##vso[build.updatebuildnumber]$newRunName"
      displayName: Set run name
