trigger: none

stages:
- stage: Terraform

  pool:
    vmImage: ubuntu-latest

  jobs:
  - job: BuildInfra
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'
