trigger: none

stages:
- stage: destroy

  pool:
    vmImage: ubuntu-latest

  jobs:
  - job: destroyRG
    steps:
    - task: azurekeyVault@2
      displayName: Retrieve secrets
      inputs:
        connectedServiceName: Azure
        keyVaultName: $(keyVaultName)
        secretsFilter: tf-token
        runAsPreJob: true

    - task: terraformInstaller@0
      displayName: Terraform install
      inputs:
        terraformVersion: '1.5.6'

    - task: replaceTokens@5
      displayName: Update token file
      inputs:
        targetFiles: $(System.DefaultWorkingDirectory)/pipelines/tfToken.json
        tokenPattern: 'azpipelines'

    - bash: |
        cd $(System.DefaultWorkingDirectory)/azure/destroy_network_watchers/
        mv $(System.DefaultWorkingDirectory)/pipelines/tfToken.json /home/vsts/.terraform.d/credentials.tfrc.json
      displayName: Terraform login

    - task: terraformCLI@0
      displayName: Terraform init
      inputs:
        command: init
        workingDirectory: $(System.DefaultWorkingDirectory)/azure/destroy_network_watchers

    - task: terraformCLI@0
      displayName: Terraform fmt
      inputs:
        command: fmt
        workingDirectory: $(System.DefaultWorkingDirectory)/azure/destroy_network_watcher

    - task: terraformCLI@0
      displayName: Terraform validate
      inputs:
        command: validate
        workingDirectory: $(System.DefaultWorkingDirectory)/azure/destroy_network_watcher

    - task: terraformCLI@0
      displayName: Import NW RG
      inputs:
        command: import
        workingDirectory: $(System.DefaultWorkingDirectory)/azure/destroy_network_watcher
        resourceAddress: azurerm_resource_group.rg
        resourceId: "subscriptions/$(ARM_SUBSCRIPTION_ID)/resourceGroups/NetworkWatcherRG"

    - task: terraformCLI@0
      displayName: Terraform destroy
      inputs:
        command: destroy
        workingDirectory: $(System.DefaultWorkingDirectory)/azure/destroy_network_watcher
