resources:
  pipelines:
  - pipeline: TFdestroy
    source: Terraform destroy infra
    project: Terraform
    trigger:
      stages:
      - Terraform_009_databricks

trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Terraform

  jobs:
  - job:
    steps:
    - checkout: none

    - task: azureKeyVault@2
      displayName: Retrieve secrets
      inputs:
        connectedServiceName: Azure
        keyVaultName: $(keyVaultName)
        secretFilter: azdoPat
        runAsPreJob: true

    - bash: |

