trigger: none

stages:
- stage: destroy

  pool:
    vmImage: ubuntu-latest

  jobs:
  - job: destroyRG
    steps:
    - task: azurekeyVault@2
      displayName: Retrieve secrets
      inputs:
        connectedServiceName: Azure
        keyVaultName: $(keyVaultName)
        secretsFilter: tf-token
        runAsPreJob: true

    - task: terraformInstaller@0
      displayName: Terraform install
      inputs:
        terraformVersion: latest

    - task: replaceTokens@5
      displayName: Update token file
      inputs:
        targetFiles: $(System.DefaultWorkingDirectory)/pipelines/tfToken.json
        tokenPattern: 'azpipelines'

    - task: replaceTokens@5
      displayName: Update subscription id
      inputs:
        targetFiles: $(System.DefaultWorkingDirectory)/azure/destroy_network_watchers/main.tf
        tokenPattern: 'azpipelines'

    - bash: |
        cd $(System.DefaultWorkingDirectory)/azure/destroy_network_watchers/
        mv $(System.DefaultWorkingDirectory)/pipelines/tfToken.json /home/vsts/.terraform.d/credentials.tfrc.json
      displayName: Terraform login

    - task: terraformCLI@0
      displayName: Terraform init
      inputs:
        command: init
        workingDirectory: $(System.DefaultWorkingDirectory)/azure/destroy_network_watchers

    - task: terraformCLI@0
      displayName: Terraform fmt
      inputs:
        command: fmt
        workingDirectory: $(System.DefaultWorkingDirectory)/azure/destroy_network_watchers

    - task: terraformCLI@0
      displayName: Terraform validate
      inputs:
        command: validate
        workingDirectory: $(System.DefaultWorkingDirectory)/azure/destroy_network_watchers

    #- task: AzureCLI@2
      #displayName: import NW RG
      #inputs:
        #azureSubscription: Azure
        #scriptType: bash
        #scriptLocation: inlineScript
        #inlineScript: |
          #cd $(System.DefaultWorkingDirectory)/azure/destroy_network_watchers
          #RESOURCE_ID=$(terraform)
          #terraform import azurerm_resource_group.rg /subscriptions/$(subscriptionId)/resourceGroups/NetworkWatcherRG

    - task: terraformCLI@0
      displayName: Terraform destroy
      inputs:
        command: destroy
        workingDirectory: $(System.DefaultWorkingDirectory)/azure/destroy_network_watchers
