---
- hosts: dbs
  gather_facts: false

  vars:
    ansible_user: zala

  tasks:
  - name: Install required tools
    become: true
    apt:
      pkg:
      - apache2
      - php
      - php-mysql
      - unzip
      state: present
  - name: Enable Apache
    become: true
    systemd:
      name: apache2
      enabled: yes
  - name: Restart Apache
    become: true
    systemd:
      name: apache2
      enabled: yes
  - name: Copy php demo file
    become: true
    template:
      src: ./info.php
      dest: /var/www/html/info.php
