apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-lb-deployment
  labels:
    name: svc-lb-deployment
spec:
  selector:
    matchLabels:
      name: svc-lb-pod
  replicas: 6
  template:
    metadata:
      name: svc-lb-pod
      labels:
        name: svc-lb-pod
    spec:
      containers:
      - name: nginx-container
        image: nginx
