#!/bin/sh

runuser -l zala -c "sudo apt update -y"
runuser -l zala -c "sudo apt install apache2 php php-mysql unzip -y"
runuser -l zala -c "sudo systemctl enable apache2.service"
runuser -l zala -c "sudo systemctl restart apache2.service"
runuser -l zala -c "cd /var/www/html/"
runuser -l zala -c "sudo touch info.php"
runuser -l zala -c "sudo chmod 666 info.php"
runuser -l zala -c "echo '<body style=\"background-color: #FFF\">' >> info.php"
runuser -l zala -c "echo '  <h1>Node PHP version</h1>' >> info.php"
runuser -l zala -c "echo '  <?php' >> info.php"
runuser -l zala -c "echo '    phpinfo();' >> info.php"
runuser -l zala -c "echo '  ?>' >> info.php"
runuser -l zala -c "echo '</body>' >> info.php"
runuser -l zala -c "sudo curl https://wordpress.org/latest.zip"
runuser -l zala -c "sudo unzip latest.zip"
runuser -l zala -c "cd wordpress/"
runuser -l zala -c "sudo cp wp-config-sample.php wp-config.php"
