---
- hosts: $(NODE2_PRIVATE_IP)
  gather_facts: false

  vars:
    ansible_user: zala
    ansible_ssh_private_key_file: $(ansibleFolder)/ssh_private

  tasks:
  - name: Update apache index page title
    become: true
    replace:
      path: /var/www/html/index.html
      regexp: 'Apache2 Default Page'
      replace: 'Apache Node 01 Page'

  - name: Change apache index background color
    become: true
    replace:
      path: /var/www/html/index.html
      regexp: 'D8DBE2'
      replace: 'FDAF17'

  - name: Change info.php page
    become: true
    replace:
      path: /var/www/html/info.php
      regexp: 'Node PHP'
      replace: 'Node 01 PHP'
