---
- hosts: all
  gather_facts: false

  vars:
    ansible_user: zala

  tasks:
  - name: run ping
    action: ping
  - name: Run apt update
    become: true
    apt:
      update_cache: yes
  - name: Run apt upgrade
    become: true
    apt:
      upgrade: dist
