---
- hosts: dbs
  gather_facts: false

  vars:
    ansible_user: zala
    ansible_ssh_private_key_file: $(ansibleFolder)/ssh_private

  tasks:
  - name: Install MariaDB & Pip
    become: true
    apt:
      pkg:
      - mariadb-server
      - python3-pip
      state: present

  - name: Install PyMySQL using Pip
    become: true
    pip:
      name: pymysql
      state: present

  - name: Enable MariaDB
    become: true
    systemd:
      name: mariadb
      enabled: yes

  - name: Edit /etc/mysql/my.cnf file
    become: true
    blockinfile:
      path: /etc/mysql/my.cnf
      block: |
        [mysqld]

        skip-network=0
        skip-bind-address

  - name: Restart MariaDB
    become: true
    systemd:
      name: mariadb
      state: restarted
      daemon_reload: yes

  - name: mariaDB root password
    become: true
    mysql_user:
      name: "{{ db_user }}"
      password: "{{ db_pass }}"
      host_all: true
      state: present
      login_user: "{{ db_user }}"
      login_password: "{{ db_pass }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock

  #- name: Edit /etc/mysql/my.cnf file
    #become: true
    #blockinfile:
      #path: /etc/mysql/my.cnf
      #block: |
        #[mysqld]

        #skip-network=0
        #skip-bind-address

  #- name: Restart MariaDB
    #become: true
    #systemd:
      #name: mariadb
      #state: restarted
      #daemon_reload: yes

  #- name: check if db user exists
    ##no_log: true
    #become: true
    #mysql_user:
      #name: "{{ db_user }}"
      #password: "{{ db_pass }}"
      #host_all: true
      #state: present
      #login_user: "{{ db_user }}"
      #login_password: "{{ db_pass }}"
      #login_unix_socket: /var/run/mysqld/mysqld.sock

  #- name: no anonymous users
    #no_log: true
    #become: true
    #mysql_user:
      #name: ''
      #state: absent
      #host_all: true
      #login_user: "{{ db_user }}"
      #login_password: "{{ db_pass }}"
      #login_unix_socket: /var/run/mysqld/mysqld.sock

  #- name: DB must exist
    #mysql_db:
      #name: "{{ db_name }}"
      #state: present
      #login_user: "{{ db_user }}"
      #login_password: "{{ db_pass }}"
      #login_unix_socket: /var/run/mysqld/mysqld.sock

  #- name: Allow db user to connect externally
    #no_log: true
    #command: 'mysql -u {{ db_user }} -p{{ db_pass }} -ne "{{ item }}"'
    #with_items:
    #- GRANT ALL PRIVILEGES ON *.* TO '{{ db_user }}'@'10.0.2.%' IDENTIFIED BY '{{ db_pass }}' WITH GRANT OPTION;
