apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: nginx2
  replicas: 3
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx-container
        image: nginx
