apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
  labels:
    name: replicaset
spec:
  selector:
    matchLabels:
      name: replicaset-pod
  replicas: 3
  template:
    metadata:
      name: nginx-pod
      labels:
        name: replicaset-pod
    spec:
      containers:
      - name: nginx-container
        image: nginx
