apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deployment
  labels:
    name: service-deployment
spec:
  selector:
    matchLabels:
      name: service-pod
  replicas: 6
  template:
    metadata:
      name: service-pod
      labels:
        name: service-pod
    spec:
      containers:
      - name: nginx-container
        image: nginx
